apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-chatbot.backend.fullname" . }}
  labels:
    {{- include "todo-chatbot.backend.labels" . | nindent 4 }}
  annotations:
    dapr.io/enabled: "true"
    dapr.io/app-id: "backend-app"
    dapr.io/app-port: "{{ .Values.backend.service.port }}"
    dapr.io/log-level: "debug"
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "todo-chatbot.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.backend.podAnnotations }}
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "backend-app"
        dapr.io/app-port: "{{ .Values.backend.service.port }}"
        dapr.io/log-level: "debug"
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "todo-chatbot.backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: {{ .Values.env.DATABASE_URL | quote }}
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}
            - name: SECRET_KEY
              value: {{ .Values.env.SECRET_KEY | quote }}
            - name: OPENROUTER_API_KEY
              value: {{ .Values.env.OPENROUTER_API_KEY | quote }}
            - name: ALGORITHM
              value: {{ .Values.env.ALGORITHM | quote }}
            - name: TOKEN_EXPIRE_DAYS
              value: {{ .Values.env.TOKEN_EXPIRE_DAYS | quote }}
            - name: FRONTEND_URL
              value: {{ printf "http://%s:3000" (include "todo-chatbot.frontend.fullname" .) | quote }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

















